package com.fictivestudios.docsvisor.apiManager.response

data class CalibrationData(
    val bio: Any,
    val certifications: Any,
    val country_code: String,
    val created_at: String,
    val date_of_birth: String,
    val device_token: String,
    val device_type: String,
    val email: String,
    val email_verified_at: String,
    val gender: String,
    val height: String,
    val id: Int,
    val image: Any,
    val is_social: Any,
    val name: String,
    val phone_no: String,
    val profession: Any,
    val profile_completed: Int,
    val role: String,
    val social_token: Any,
    val social_type: Any,
    val updated_at: String,
    val watch_calibration: Int,
    val watch_connectivity: Int,
    val watch_imei: String,
    val watch_user_id: String,
    val weight: String
)